### ISSUE TITLE
What about a pure TS release ?

### ISSUE THREAD

**Issue by lpenet** [samchon/tstl#1]
Hi.

As a STL lover, I quickly found your project when looking for some kind of multimap for typescript.

It looks very interesting, but I do not really like the way it is actually packaged. I think it could be interesting to release it as typescript only and let the developper decides how to compile/bundle it.

The original STL was a set of C++ headers... And that was _sooooo_ great. Having the same for TS would be great too.

I am working actually on an angular 2 app written in es2015. I think I will end pulling your project and import the TS file directly... Howewer, having an npm package with the TS sources ready for import would be great.

**Comment by samchon** [comment]
I'm providing this TypeScript-STL as a NPM module with compiled JS file and D.TS file.

However, you want me to compose the NPM module not only with JS and D.TS files, but also with original TS files. And now, you're temporarily downloading my original TS files and compile them to ES2015 mode by yourself. Is that right?

**Comment by samchon** [comment]
I don't know ES2015 and its modular system. I will write my opinion following what I've learned. If there's something wrong what I've known, then please point out it. If you know a great solution supporting multiple modular systems and pure include (via HTML) at once, then please inform me. Sending a pull request will be much better.

--------

Unfortunately, source code, original TS files of TypeScript-STL are merged into one file with --outFile option. Thus it's not a matter to realizing original TS files in NPM module, but you can't use ```import``` command with the original TS files. Exporting TypeScript-STL as CommonJS is done by hard coding like such below:
  - https://github.com/samchon/typescript-stl/blob/master/ts/src/std/miscellaneous/exports.ts#L24-L27

Regardless of the ES version whether ES5 or ES6, you can import TypeScript-STL only in NodeJS (or with Browserify). In web, you've to include typescript-stl.js in level of HTML document.

## NodeJS
###### Command Line
```bash
npm install -g typescript-stl
tsd install typescript-stl
```

##### TS File
```typescript
/// <reference path="typings/typescript-stl/typescript-stl.d.ts" />
import std = require("typescript-stl");
```

## Web
###### HTML File
```html
<html>
<head>
    <title> Include TypeScript-STL </title>
    <script src="include/typescript-stl.js"></script>
</head>
```

**Comment by samchon** [comment]
The next major update, v2.0, will make it possible.

**Comment by samchon** [comment]
https://github.com/samchon/tstl/tree/module

```typescript
import {Vector} from "tstl/vector";
import * as alg from "tstl/algorithm";
```

I've tried your method, separating modules instead of the ordinary merging, however, it seems that much difficult to use than before.

**Comment by lpenet** [comment]
Thanks !

**Comment by samchon** [comment]
I'm sorry for announcing here too late. The detailed story is on the `releases` sections.
  - https://github.com/samchon/tstl/releases/tag/v2.0.5

**Comment by lpenet** [comment]
Do not be sorry ! You are doing great ! Two words : thank you !
