### ISSUE TITLE
Tsconfig target ES2020

### ISSUE THREAD

**Issue by nguyenhothanhtam0709** [samchon/tstl#116]
Hi @samchon, I see that in rollup.config.js, Typescript targets ES2020 but in tsconfig.json it targets ES5. Can you change  Typescript's target to at least ES2017 to get benefit from Javascript's native async await?

**Comment by samchon** [comment]
`typia` does not have any asynchrous function feature. 

Only setup/generation wizard are using the `await` keyword.

**Comment by nguyenhothanhtam0709** [comment]
@samchon , Do you mean that this library target es5 because it related to **typia**?

**Comment by samchon** [comment]
Oops, I mistook this for the typia repository.

I do not have plan to build to ES2017+. It is because of legacy projects using TSTL, and explicit `await` keyword is not such significantly beneficial for such TSTL features' case.

**Comment by nguyenhothanhtam0709** [comment]
@samchon , can I make pr to target es2017 or fork this repo and target es2017 by myself?

**Comment by samchon** [comment]
It is okay to making a fork repo and npm registry.

**Comment by nguyenhothanhtam0709** [comment]
Thank you so much.
