### ISSUE TITLE
ERROR in node_modules/tstl/base/containers/MapContainer.d.ts

### ISSUE THREAD

**Issue by AirLancer** [samchon/tstl#13]
I just installed sxml 1.0.3 and afterwards I can't build anymore.
I have typscript version 2.7.2.
I can't upgrade any further for lack of angular cli support of newer versions.

ERROR in node_modules/tstl/base/containers/MapContainer.d.ts(107,114): error TS1005: ';' expected.
node_modules/tstl/base/containers/MapContainer.d.ts(107,180): error TS1005: '(' expected.
node_modules/tstl/base/containers/MapContainer.d.ts(107,217): error TS1005: '(' expected.
node_modules/tstl/base/containers/SetContainer.d.ts(109,108): error TS1005: ';' expected.
node_modules/tstl/base/containers/SetContainer.d.ts(109,171): error TS1005: '(' expected.
node_modules/tstl/base/containers/SetContainer.d.ts(109,205): error TS1005: '(' expected.

To create a minimal angular app that can reproduce this it only takes:
`ng new sxml-test-app`
`cd sxml-test-app`
`ng build` (not sure if this one is imporant)
`npm install --save sxml`

add the following to app.component.ts:
`import sxml = require('sxml');`
or
`import { XML } from 'sxml';`

`ng build`

That is when the error above appears.

**Comment by samchon** [comment]
I recommend you to upgrade the TypeScript to latest one (`2.9`)

**Comment by AirLancer** [comment]
As I've written above, the usage of angular prohibits a newer version of TypeScript for now. The angular CLI is limited to 2.8.0.
I guess this will eventually resolve itself when the angular CLI supports newer TypeScript versions. But I think this is quite a noteworthy limitation.
May be good to put that in the readme or better yet, put TS 2.9 in the dependencies of the package json to prohibit the use with older versions.

**Comment by samchon** [comment]
Well, many people using `TypeScript`, they've installed the `TypeScript` in global level. Is it possible to let user of `TSTL` to upgrade the `TypeScript` to latest one by `package.json`? Can you show me an example?
  - `npm install -g typescript`

> Anyway, using `TSTL` is also possible in the `TS v2.8`.

**Comment by AirLancer** [comment]
In the projects I've seen it, it was always like this in the package.json:
`"devDependencies": {
    "typescript": "^2.8.0"
  }`

Sadly, the angular cli make a hard cut at TS 2.8.0, and there was only the release candiate (2.8.0-rc) and immediatly after it was 2.8.1.
I ende up parsing the files myself, which works well enough for my use case.
