### ISSUE TITLE
Error on List.insert for erased iterator

### ISSUE THREAD

**Issue by samchon** [samchon/tstl#37]
### Summary
  - **TSTL Version**: All versions
  - **Expected behavior**: List.insert does not work on erased iterator
  - **Actual behavior**: No error List.insert on erased iterator and it returns wrong `size()`.

### Code occuring the bug
```typescript
import std = require("tstl");

function main(): void
{
    let v: std.List<number> = new std.List();
    for (let i: number = 0; i < 10; ++i)
        v.push_back(i);

    let first: std.List.Iterator<number> = std.advance(v.begin(), 2);
    let mid: std.List.Iterator<number> = std.advance(v.begin(), 5);
    let last: std.List.Iterator<number> = std.advance(v.begin(), 8);

    v.erase(first, last);
    v.insert(mid, 4, -1);

    console.log("List.size(): #" + v.size());
    console.log("--------------------------");

    let size: number = 0;
    for (let elem of v)
    {
        console.log(elem);
        ++size;
    }
    console.log("--------------------------");
    console.log("Actual size: #" + size);
}
main();
```

> ```bash
> List.size(): #8
> --------------------------
> 0
> 1
> 8
> 9
> --------------------------
> Actual size: #4
>

**Comment by Lyoko-Jeremie** [comment]
in my view.

when the ```v.erase(first, last);``` be excuted. all the iterator of the container be invalid. 
this is a correct behavior on C++.
because the container maybe need malloc new memory and copy all the item in the container to new place.

<hr/>

BTW: i love this project. thank you for your work. (*^▽^*)

**Comment by samchon** [comment]
## Solution
In my think, there's a way to solving the problem and preventing mis-computed size by `List.size()` method. The way is `List.Iterator` to have an additional property `List.Iterator.erased` and let `List.erase()` method to change the property value to be `true` like below code.

```typescript
class List<T>
{
    private begin_: List.Iterator<T>;
    private end_: List.Iterator<T>;
    private size_: number;

    public erase(first: List.Iterator<T>, last: List.Iterator<T>): List.Iterator<T>
    {
        // DO ERASE
        this.size_ -= advance(first, last);
        first.prev_.next_ = last;
        last.prev_ = first.prev_;

        // AFTER ERASURE
        for (let it = first; !it.equals(last); it = it.next())
            it.erased_= true;
    }
}

namespace List
{
    export class Iterator<T>
    {
        private prev_: Iterator<T>;
        private next_: Iterator<T>;
        private value_: T;
        private erased_: boolean;
    }
}
```

## Recognition
However, the solution may harm main advantage of the doubly-linked-list: fast erasure O(1) on middle elements. To keep the O(1) complexity, there's an alternative optimistic way to ignoring such error and just anticipating users not to using erased iterator to insert element(s); optimistic assumption.

The C++ STL takes the optimistic assumption. Thus `std::list<T>::iterator` does not have erasure property and occurs same error like **TSTL**.

```cpp
#include <iostream>
#include <list>
#include <iterator>

using namespace std;

template <class Container>
auto nth(Container &v, int n) -> typename Container::iterator
{
    typename Container::iterator it = v.begin();
    advance(it, n);
    return it;
}

int main()
{
    list<int> v;
    for (int i = 0; i < 10; ++i)
        v.push_back(i);
        
    list<int>::iterator first = nth(v, 2);
    list<int>::iterator mid = nth(v, 5);
    list<int>::iterator last = nth(v, 8);

    v.erase(first, last);
    v.insert(mid, 4, -1);
    
    cout << "List.size(): #" << v.size() << endl;
    cout << "--------------------------" << endl;
    
    size_t size = 0;
    for (auto it = v.begin(); it != v.end(); ++it)
    {
        int val = *it;
        cout << val << endl;
        ++size;
    }
    cout << "--------------------------" << endl;
    cout << "Actual size: #" << size << endl;

    return 0;
}
```

## In another view
```typescript
class List<T>
{
    public erase(first: List.Iterator<T>, last: List.Iterator<T>): List.Iterator<T>
    {
        // ERASURE - O(1)
        first.prev_.next_ = last;
        last.prev_ = first.prev_;

       // Re-defining size - O(n)
       this.size_ -= advance(first, last);

        // Set erasure flag to be true - O(n)
        for (let it = first; !it.equals(last); it = it.next())
            it.erased_= true;
    }
}
```

In academically, linked-list can erase elements in O(1). However, in actually, `std.List.erase()` method requires re-definition of container size and the re-difining `std.List.size()` makes `std.List.erase()` to be O(n).

Considering characteristics of linked-list's iterator, computing total size of erased elements requires full iteration of them. The full iteration violates the O(1). Because the O(1) already being broken, how about considering to add erased_ property onto the `List.Iterator` ?
