### ISSUE TITLE
How do i contribute this project?

### ISSUE THREAD

**Issue by swimyoung** [samchon/tstl#4]
Hi, 
this project is amazing. i am interested in this project. can you tell me how to contribute this open source. ( coding convention, test case, commit message rule etc.. anything that i should know.. )

**Comment by samchon** [comment]
The contribution guides will be published.

**Comment by samchon** [comment]
Read the [CONTRIBUTING.md](https://github.com/samchon/tstl/blob/master/CONTRIBUTING.md)

**Comment by swimyoung** [comment]
thank you for replying 👍
