### ISSUE TITLE
Find a way to publishing npm module with ts files

### ISSUE THREAD

**Issue by samchon** [samchon/tstl#68]
**TSTL** is designed to the TypeScript users. As many features in the **TSTL** are using generic types and strict restrictions, pure JS users cannot take advantages of such type and generic restrictions. Therefore, in the case of **TSTL**, it would better to publish `ts` files and let users to compile by themselves, instead of publishing compiled `js` files and their declaration `d.ts` files.

However, the TypeScript doesn't support the feature, publishing npm module with `ts` files. Therefore, I need to write a suggestion on the TypeScript issue, requesting the way to publishing the npm module with the `ts` files.

**Comment by chinesedfan** [comment]
Looks like this issue has been resolved?

**Comment by samchon** [comment]
There's no way even if using Deno. Sorry for late closing
