### ISSUE TITLE
it seems that Semaphore try_acquire_for has some bug

### ISSUE THREAD

**Issue by chacent** [samchon/tstl#70]
it occors multiple times ,at last the bug always(at least two diff scene) found at try_acquire_for and release,,but i can't repeat it with simply code. i believe that it has a bug

**Comment by samchon** [comment]
I'm going to review implementation of the `Semaphore` class in this weekend, may Sunday. However, it would be better you to provide me more detailed information or some of the test code who can reproduce the bug.

**Comment by chacent** [comment]
the counter seems going bad when lots of try_acquire_for,at last semaphore can't be acquired. i try to make the scene but i failed,It's not easy to reproduce

**Comment by chacent** [comment]
i'm sure that my code has release every time,and the function acquire do well always

**Comment by chacent** [comment]
my code is like this
(async()=>{
        while(true){
            if(await s.try_acquire_for(1000)){
                (async()=>{
                    const wait = Math.ceil(Math.random()*10);
                    console.log(1,wait);
                    await new Promise(s=>setTimeout(s,wait));
                })().finally(()=>s.release());
            }
        }
    })();

**Comment by chacent** [comment]
This is the code that i actually used
`
thread_middleware(){
        return async(ctx,next)=>{
            if(await this[$semaphore].try_acquire_for(1000)){
                try{
                    await next();
                }finally {
                    this[$semaphore].release();
                }
            }else{
                throw new Error('server busy');
            }
        }
    }
`

**Comment by chacent** [comment]
sorry for that i don't know how to format the code

**Comment by samchon** [comment]
I've tried your 1st code like below and it seems no error.

```typescript
import { Semaphore, randint, sleep_for } from "tstl";

async function main(): Promise<void>
{
    let s: Semaphore = new Semaphore(4);
    let minimum: number = 500;
    let maximum: number = 4000;

    while(true)
    {
        if (await s.try_acquire_for(1000) === true)
        {
            (async () =>
            {
                const time = randint(minimum, maximum);
                console.log("success, sleep_for", time, "ms");

                await sleep_for(time);
                await s.release();
            })();
        }
        else
            console.log("failed");
    }
}
main();
```

> ```bash
> success, sleep_for 1344 ms
> success, sleep_for 2387 ms
> success, sleep_for 1774 ms
> success, sleep_for 3366 ms
> failed
> success, sleep_for 3734 ms
> success, sleep_for 3435 ms
> success, sleep_for 612 ms
> success, sleep_for 921 ms
> success, sleep_for 3230 ms
> success, sleep_for 2549 ms
> failed
> success, sleep_for 3902 ms
> success, sleep_for 3902 ms
> failed
> success, sleep_for 2585 ms
> success, sleep_for 984 ms
> success, sleep_for 2381 ms
> ```

**Comment by chacent** [comment]
yes,i found no error when test,and this is my test code.but when actual project it occors.now i use acquire instead. i will focus with this later

**Comment by samchon** [comment]
I'd found a mistaken code that can occur a runtime error in the `Semaphore._Cancel()` method: 

https://github.com/samchon/tstl/blob/228e2471f1581c47df72990127543b9fc4cae098/src/thread/Semaphore.ts#L145-L146

Therefore, I've patched the tstl to `2.4.8` to fix the code like below:

https://github.com/samchon/tstl/blob/4be6620f100179f5639216bc85bfe7bfc55588cf/src/thread/Semaphore.ts#L140-L141

Anyway, looking at your 2nd code, it seems @chacent, you're using the `nestjs` framework, right? I'll test similar code by creating a test web-server project using the `nestjs` at next weekend, may Saturday. Until the next wekkend, I hope @chacent you to upgrade your project to using the new `tstl@2.4.8` and tell me if same error occurs.

**Comment by chacent** [comment]
Thank you. I'm sure this problem has no relation with the library I used. If I have time to try to find another piece of code that I made a mistake last time, it must be a problem of counting logic, which may be caused by reentry

**Comment by chacent** [comment]
and maybe your patch code works, i'll try tomorrow

**Comment by chacent** [comment]
my framework used is koa,just ignore it,thanks
